/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-10-24 15:08:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fweb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class card4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/fweb/Top.jsp", Long.valueOf(1571243350121L));
    _jspx_dependants.put("/fweb/Bottom.jsp", Long.valueOf(1571238713987L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"imgs/favicon.ico\" >\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" >\r\n");
      out.write("<title> 꿀비 </title>\r\n");
      out.write("<style>\r\n");
      out.write("   #container{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      font-family: '돋움',Dotum,Helvetica,sans-serif;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding-bottom: 0;\r\n");
      out.write("   }\r\n");
      out.write("   .collect_wrap{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      width: 1098px;\r\n");
      out.write("      margin: 0 auto 90px;\r\n");
      out.write("      border-bottom: 1px solid #e5e5e5;\r\n");
      out.write("      border-top: 1px solid #e5e5e5;\r\n");
      out.write("      background: url(https://ssl.pstatic.net/happyimg2/img/mainhome/bg_crowd.gif) repeat-y;\r\n");
      out.write("   }\r\n");
      out.write("   .collect_content{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      float: left;\r\n");
      out.write("      width: 816px;\r\n");
      out.write("      padding: 60px 94px 90px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("   }\r\n");
      out.write("   .collect_side{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      float: left;\r\n");
      out.write("      width: 282px;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("   }\r\n");
      out.write("   .theme{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      font-size: 17px;\r\n");
      out.write("      letter-spacing: -.06em;\r\n");
      out.write("      line-height: 1;\r\n");
      out.write("      color: #E5CF51;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("   }\r\n");
      out.write("   .tit{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      margin-top: 16px;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      display: block;\r\n");
      out.write("      clear: both;\r\n");
      out.write("      content: '';\r\n");
      out.write("      margin-bottom: 15px;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      font-size: 36px;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      color: #222;\r\n");
      out.write("      letter-spacing: .4px;\r\n");
      out.write("      line-height: 40px;\r\n");
      out.write("   }\r\n");
      out.write("   .tab_cont{\r\n");
      out.write("      -webkit-font-smoothing: antialiased;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      font-family: NanumBarunGothic,\"나눔바른고딕\",\"Nanum Barun Gothic\",Sans-serif;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      margin: 57px 0 55px;\r\n");
      out.write("   }\r\n");
      out.write("   .t_group{\r\n");
      out.write("      font-family: 'NanumBarunGothic','Malgun Gothic','맑은 고딕','돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #2f2f2f;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      line-height: 140%;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      border-top: 1px solid #e0e0e0;\r\n");
      out.write("      height: 47px;\r\n");
      out.write("   }\r\n");
      out.write("   dl{\r\n");
      out.write("      font-family: 'NanumBarunGothic','Malgun Gothic','맑은 고딕','돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #2f2f2f;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      line-height: 140%;\r\n");
      out.write("      margin: 0 !important;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      float: left;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding-left: 120px;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      height: 47px;\r\n");
      out.write("   }\r\n");
      out.write("   dt{\r\n");
      out.write("      font-family: 'NanumBarunGothic','Malgun Gothic','맑은 고딕','돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #2f2f2f;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      line-height: 140%;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 120px;\r\n");
      out.write("      height: 47px;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      background: #f8f8f8;\r\n");
      out.write("   }\r\n");
      out.write("   dd{\r\n");
      out.write("      font-family: 'NanumBarunGothic','Malgun Gothic','맑은 고딕','돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #2f2f2f;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      line-height: 140%;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 47px;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("   }\r\n");
      out.write("   .side_tit{\r\n");
      out.write("      font-family: 'NanumBarunGothic','Malgun Gothic','맑은 고딕','돋움',Dotum,Helvetica,'Apple SD Gothic Neo',Sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #2f2f2f;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      line-height: 140%;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      margin: 0 0 20px 0;\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      background: #E5CF51;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("   }\r\n");
      out.write("   .try{\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("      margin: 10px 90px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      background: none;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      min-height: 35px;\r\n");
      out.write("      padding: 5px 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      border: 1px solid #cdcdcd;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      vertical-align: middle;\r\n");
      out.write("      line-height: 160%;\r\n");
      out.write("      border-color: #E5CF51;\r\n");
      out.write("      color: #E5CF51!important;\r\n");
      out.write("   }\r\n");
      out.write("   .try:focus {\r\n");
      out.write("      outline-color: #B2977B;\r\n");
      out.write("   }\r\n");
      out.write("   .stitle {\r\n");
      out.write("   \t\tfont-size:23px;\r\n");
      out.write("   \t\tpadding-top:30px;\r\n");
      out.write("   \t\tmargin:0px;\r\n");
      out.write("   \t\tfont-weight:500;\r\n");
      out.write("   \t\tcolor:#444;\r\n");
      out.write("   }\r\n");
      out.write("   .scont {\r\n");
      out.write("   \t\tpadding-top:17px;\r\n");
      out.write("   \t\tfont-size:17px;\r\n");
      out.write("   }\r\n");
      out.write("   .dimg {\r\n");
      out.write("   \t\tpadding-top:20px;\r\n");
      out.write("   \t\twidth: 628px;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tmargin-top:30px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.today{\r\n");
      out.write("\t\tpadding-top:7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.searchimg {\r\n");
      out.write("\t\twidth:18px;\r\n");
      out.write("\t\theight:18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginimg {\r\n");
      out.write("\t\twidth:30px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-right:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menudiv{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding-top:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem {\r\n");
      out.write("\t\tpadding: 0px 30px 0px 30px;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:600;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tfont-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem:hover {\r\n");
      out.write("\t\t/* color:#C3A88C; */\r\n");
      out.write("\t\tcolor:#EACC1A;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu {\r\n");
      out.write("\t\tcolor:#AB3839;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu:hover {\r\n");
      out.write("\t\tcolor:#F86C6B;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* .bcolor {\r\n");
      out.write("\t\tbackground:#888888;\r\n");
      out.write("\t} */\r\n");
      out.write("\t.logo {\r\n");
      out.write("\t\twidth:20px;\r\n");
      out.write("\t\theight:20px;\r\n");
      out.write("\t\tmargin-left:15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\" class=\"header\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<img class =\"logo\" src=\"imgs/logo.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-5\"></div>\r\n");
      out.write("\t\t<div class=\"col-sm-2 today\">\r\n");
      out.write("\t\t\t<span> Today with </span>\r\n");
      out.write("\t\t\t<span> 0 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\" aria-label=\"Search\" aria-describedby=\"button-addon2\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"><img class =\"searchimg\" src=\"imgs/search.png\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t<img class =\"loginimg\" src=\"imgs/loginimg.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"menudiv\">\r\n");
      out.write("\t\t\t\t<a href=\"donation.jsp\" class=\"menuitem give\" aria-current=\"false\"> 기부 </a>\r\n");
      out.write("\t\t\t\t<a href=\"volunteer.jsp\" class=\"menuitem\" aria-current=\"false\"> 봉사 </a>\r\n");
      out.write("\t\t\t\t<a href=\"campaign.jsp\" class=\"menuitem\" aria-current=\"false\"> 캠페인 </a>\r\n");
      out.write("\t\t\t\t<a href=\"drank.jsp\" class=\"menuitem\" aria-current=\"false\"> 기부순위 </a>\r\n");
      out.write("\t\t\t\t<a href=\"gogodonation.jsp\" class=\"menuitem redmenu\" aria-current=\"false\"> 기부해요 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("   <div class=\"collect_wrap\">\r\n");
      out.write("      <div class=\"collect_content\">\r\n");
      out.write("         <a href=\"#\" class=\"theme\">기부  &gt; 분류</a>\r\n");
      out.write("         <h3 class=\"tit\"> 독거어르신들에게 특별한 하루를 선물하세요!! </h3>\r\n");
      out.write("         <div class=\"tab_cont\">\r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl style=\"margin:0;\">\r\n");
      out.write("                  <dt>기부 기간</dt> <dd>2019-09-01~ 2020-11-30</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl>\r\n");
      out.write("                  <dt>기부 단체</dt> <dd>용산재가노인지원센터</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img src=\"imgs/cimg4.jpg\" class=\"dimg\">\r\n");
      out.write("            <p class=\"stitle\"> 90세가 넘도록 생일을 잊고 지내시는 노순자 할머님 (가명, 91세) </p>\r\n");
      out.write("            <p class=\"scont\">\r\n");
      out.write("\t\t\t\t슬하에 자식없이 평생 혼자 사신 노할머님은 언제나 큰 소리로 밝은 미소를 지으시며 우리를 맞으십니다.\t<br>\r\n");
      out.write("\t\t\t\t머리는 새하얀 백발이며 귀가 거의 들리지 않아 보청기 없이는 의사소통이 힘들지만,\t\t<br>\r\n");
      out.write("\t\t\t\t다른 어르신들이 앓고 있는 만성질환 (고혈압, 당뇨, 관절염, 통증 등) 하나 없이 건강한 편입니다.\t<br>\r\n");
      out.write("\t\t\t\t그러나 90세가 넘어가면서 치매증상을 보이며 혼자 새벽에 배회하기도 하고\t<br>\r\n");
      out.write("\t\t\t\t도둑이 들어와 물건을 훔쳐갔다는 말씀을 자주 하십니다.\t<br>\r\n");
      out.write("\t\t\t\t혼자 지내다보니 무료하신 시간이 많아 경로당, 노인대학 등에 열심히 다니시고,\t<br>\r\n");
      out.write("\t\t\t\t시간이 나면 집 앞 공원에 나가 지나가는 사람들을 쳐다보며 지내시곤 합니다.\t\t<br>\r\n");
      out.write("\t\t\t\t어제가 오늘 같고, 오늘이 내일 같은 할머님에게 지나가는 세월은 무심하기만 합니다.\t<br>\r\n");
      out.write("\t\t\t\t구순이 지났지만 일평생 생일을 챙겨주는 사람없이 외롭게 지내시는 할머님에게\t<br>\r\n");
      out.write("\t\t\t\t이제라도 특별한 하루를 선물하고 싶습니다.\t<br>\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("            <p class=\"stitle\"> 평생을 눈물로 보내신 김숙희 할머님 (가명, 90세) </p>\r\n");
      out.write("            <p class=\"scont\">\r\n");
      out.write("\t\t\t\t김할머님은 씨받이로 들어간 가정에서 본처의 학대를 받으며 평생을 지내셨습니다.\t<br>\r\n");
      out.write("\t\t\t\t다행히 아들 둘을 낳고 80세가 넘어서야 본처에게서 인정을 받고 뒤늦게 평안을 찾았지만,\t<br>\r\n");
      out.write("\t\t\t\t서른이 넘도록 직장도 없이 집에서 빈둥거리며 용돈을 달라고 행패부리는\t<br>\r\n");
      out.write("\t\t\t\t둘째 아들 때문에 날마다 눈물로 세월을 보내고 있습니다.\t<br>\r\n");
      out.write("\t\t\t\t수급비를 모아 아들 용돈에 보태곤 하지만, 아들의 학대가 점점 심해지면서\t<br>\r\n");
      out.write("\t\t\t\t더 이상 살고 싶지 않다며 하소연하는 김할머님을 보면 가슴이 먹먹합니다.\t<br>\r\n");
      out.write("\t\t\t\t평생을 눈물로 보내시며 올해 구순이 되었지만 누구 한 사람 할머님의\t<br>\r\n");
      out.write("\t\t\t\t생신을 챙겨주는 사람이 없는 상황에서 할머님의 서러움과 슬픔이 쌓여가고 있습니다.\t<br>\r\n");
      out.write("\t\t\t\t김할머님에게 단 하루만이라도 서러움과 슬픔을 잊고 행복한 시간이 되도록\t<br>\r\n");
      out.write("\t\t\t\t이웃분들과 함께 어르신의 구순잔치를 베풀고자 합니다.\t<br>\r\n");
      out.write("            </p>\r\n");
      out.write("            \r\n");
      out.write("            <p class=\"stitle\"> 90세가 넘은 어르신들에게 구순잔치를 해드리고자 합니다! </p>\r\n");
      out.write("            <p class=\"scont\">\r\n");
      out.write("\t\t\t\t현재 저희 센터에서 서비스를 제공하고 있는 재가어르신 중에서 \t<br>\r\n");
      out.write("\t\t\t\t구순이 넘어 혼자 사는 어르신들의 수가 10여명이 됩니다. \t<br>\r\n");
      out.write("\t\t\t\t이 어르신들을 모시고 지역주민과 친구분들과  \t<br>\r\n");
      out.write("\t\t\t\t함께 어르신들을 위한 구순잔치를 해드리고 싶습니다. \t<br>\r\n");
      out.write("\t\t\t\t고운 한복도 준비하고, 잔치상도 준비하고, 노래와 춤 등 다양한 프로그램으로  \t<br>\r\n");
      out.write("\t\t\t\t어르신들을 행복하게 해드리고 싶습니다. 또한 어르신들에게 선물도 드리고  \t<br>\r\n");
      out.write("\t\t\t\t지금껏 살아온 나날 중 가장 행복한 시간을 만들어드리고 싶습니다. \t<br>\r\n");
      out.write("\t\t\t\t외로움과 서러움으로 평생을 보내시는 어르신들을 위한 구순잔치에 많은 분들의 관심과 응원을 부탁드립니다.\t    \t<br>        \r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl style=\"margin:0;\">\r\n");
      out.write("                  <dt style=\"background:#fff;border-right:1px solid #e0e0e0;\">기부 기간</dt> <dd>2019-09-01~ 2020-11-30</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl style=\"margin:0;\">\r\n");
      out.write("                  <dt style=\"background:#fff;border-right:1px solid #e0e0e0;\">기부 대상</dt> <dd>독거 어르신</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl style=\"margin:0;\">\r\n");
      out.write("                  <dt style=\"background:#fff;border-right:1px solid #e0e0e0;\">대상 수</dt> <dd>15명</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"t_group\">\r\n");
      out.write("               <dl>\r\n");
      out.write("                  <dt style=\"background:#fff;border-right:1px solid #e0e0e0;\">기대 효과</dt> <dd>- 독거어르신 15명에게 구순잔치 실시<br> - 지역주민들과 함께 어르신 생신 축하하여 지역공동체 활성화 기여</dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"collect_side\">\r\n");
      out.write("         <div class=\"side_tit\">기부 참여</div>\r\n");
      out.write("         <div class=\"t_group\">\r\n");
      out.write("            <dl style=\"margin:0;\">\r\n");
      out.write("               <dt>구분</dt> \r\n");
      out.write("               <dd>\r\n");
      out.write("                  <input type=\"radio\" name=\"chk_btn\" value=\"individual\" checked=\"checked\">개인\r\n");
      out.write("                  <input type=\"radio\" name=\"chk_btn\" value=\"group\">단체\r\n");
      out.write("               </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"t_group\">\r\n");
      out.write("            <dl style=\"margin:0;\">\r\n");
      out.write("               <dt>이름</dt> \r\n");
      out.write("               <dd> <input type=\"text\" name=\"name\" size=\"15\"> </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"t_group\">\r\n");
      out.write("            <dl style=\"margin:0;\">\r\n");
      out.write("               <dt>연락처</dt> \r\n");
      out.write("               <dd>\r\n");
      out.write("                  <input type=\"text\" name=\"name\" size=\"15\">\r\n");
      out.write("               </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"t_group\" >\r\n");
      out.write("            <dl style=\"margin:0;\">\r\n");
      out.write("               <dt>이메일</dt> \r\n");
      out.write("               <dd> <input type=\"text\" name=\"name\" size=\"15\"> </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("         </div>\r\n");
      out.write("         <button type=\"button\" onclick=\"#\" class=\"try\">신청하기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.fdiv{\r\n");
      out.write("\t\t/* background-color:#D1C6BA; */\r\n");
      out.write("\t\tbackground-color:#DDD18D;\r\n");
      out.write("\t\tmargin-top:20px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t\tpadding: 20px 30px 20px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.companyimg{\r\n");
      out.write("\t\twidth:15px;\r\n");
      out.write("\t\theight:15px;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"fdiv\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 서울특별시 성동구 살곶이길 200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 대표전화 : 02-2290-2200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<img class=\"companyimg\" src=\"imgs/company.png\">\r\n");
      out.write("\t\t<span> Copyright © InsideOut. All Rights Ressrved. </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
