/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-10-24 15:07:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fweb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import org.jsoup.select.Elements;
import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public final class donation22_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/fweb/Top.jsp", Long.valueOf(1571243350121L));
    _jspx_dependants.put("/fweb/Bottom.jsp", Long.valueOf(1571238713987L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>꿀비</title>\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"imgs/favicon.ico\" >\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" >\r\n");
      out.write("<style>\r\n");
      out.write("\t#container {\r\n");
      out.write("\t\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t\tfont-family: '돋움', Dotum, Helvetica, sans-serif;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tcolor: #666;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding-bottom: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.card_wrap {\r\n");
      out.write("\t\tfont-family: NanumBarunGothic, dotum, Sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\tline-height: 19px;\r\n");
      out.write("\t\tcolor: #202020;\r\n");
      out.write("\t\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t\twidth: 1164px;\r\n");
      out.write("\t\tmargin: 12px 0 -24px -24px;\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.card {\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\tline-height: 19px;\r\n");
      out.write("\t\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor: inherit;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\twidth: 267px;\r\n");
      out.write("\t\theight: 350px;\r\n");
      out.write("\t\tmargin: 0 0 24px 24px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tbackground-color: #fff;\r\n");
      out.write("\t\tfont-family: NanumSquareWebFont, dotum, Sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.card_img {\r\n");
      out.write("\t\twidth: 266px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.card_content {\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\tline-height: 19px;\r\n");
      out.write("\t\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t\tcolor: inherit;\r\n");
      out.write("\t\tfont-family: NanumSquareWebFont, dotum, Sans-serif;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t\tpadding: 21px 20px 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.card_title {\r\n");
      out.write("\t\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t\tfont-family: NanumSquareWebFont, dotum, Sans-serif;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\ttext-overflow: ellipsis;\r\n");
      out.write("\t\tdisplay: -webkit-box;\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tline-height: 25px;\r\n");
      out.write("\t\tword-wrap: break-word;\r\n");
      out.write("\t\tword-break: break-all;\r\n");
      out.write("\t\t-webkit-line-clamp: 2;\r\n");
      out.write("\t\t-webkit-box-orient: vertical;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tfont-weight: 700;\r\n");
      out.write("\t\tletter-spacing: -.5px;\r\n");
      out.write("\t\tcolor: #333;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menuitem {\r\n");
      out.write("\t\tpadding: 0px 20px 0px 20px;\r\n");
      out.write("\t\tfont-size: 25px;\r\n");
      out.write("\t\tfont-weight: 600;\r\n");
      out.write("\t\tcolor: #000;\r\n");
      out.write("\t\tfont-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menuitem:hover {\r\n");
      out.write("\t\tcolor: #E5CF51;;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.info_bx {\r\n");
      out.write("\t\tmargin-top: 2px;\r\n");
      out.write("\t\tmargin-left: 10px;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.s_bx {\r\n");
      out.write("\t\tletter-spacing: -.5px;\r\n");
      out.write("\t\tmargin-top: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.category {\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tfont-weight: 700;\r\n");
      out.write("\t\tcolor: #E5CF51;;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.association {\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tfont-weight: 700;\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.ss_bx {\r\n");
      out.write("\t\tmargin-top: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.col-12 {\r\n");
      out.write("\t\tmargin-left: 35%;\r\n");
      out.write("\t\tword-spacing:-10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#btn{\r\n");
      out.write("\tborder: 1px solid #E5CF51;;\r\n");
      out.write("\tbackground-color:#FFFFFF;\r\n");
      out.write("\tcolor:#E5CF51;;\r\n");
      out.write("\tfont-weight:700;\r\n");
      out.write("\tpadding:5px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#btn:hover{\r\n");
      out.write("\tcolor:#FFFFFF;\r\n");
      out.write("\tbackground-color:#E5CF51;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"Resources/jquery/jquery-3.4.1.min.js\"></script>\r\n");

	//저장할 List 선언
	List<String> titles = new ArrayList<String>();
	List<String> urls = new ArrayList<String>();
	List<String> imgs = new ArrayList<String>();
	
	//gfoundation 코드
	for(int n=1; n<6; n++) {
		//url 할당
		String gurl = "https://www.gfound.org/bbs/board.php?bo_table=support_1&page="+n;
		String gselector = "div.bo_list";
	    Document gdoc = null;
	    
	    try {
	        gdoc = Jsoup.connect(gurl).get(); // 1. get방식의 URL에 연결해서 가져온 값을 doc에 담는다.
	    } catch (IOException e) {
	        System.out.println(e.getMessage());
	    }
	    
	    //메인 요소 선택
	    Elements gfound = gdoc.select("ul>li");
	    
	    //gfound title ////// title이 비어있는건 어떻게 처리 할건지ㅠㅠ...
	    String gtitle = gfound.select("p.s_list_stit").html();
	    String[] gtitles = gfound.select("p.s_list_stit").html().split("\n");
	    for(int t=0; t<gtitles.length; t++) {
	    	if(gtitles[t] == ""){
	    		titles.add(" ");
	    	}else{
	    		titles.add(gtitles[t]);
	    	}
	    	
	    }
	    
	    //gfound url
		String[] gurls = gfound.select("span.s_list_btn").html().split("\n");
		for(int u=0; u<gurls.length; u++) {
			//substring 이용해서 필요한 url 부분만 자름
			gurls[u] = gurls[u].substring(9, 92);
			urls.add(gurls[u]);
		}
		
		//gfound img
		String[] gimgs = gfound.select("div.s_list_phot>a").html().split("\n");
		for(int i=0; i<gimgs.length; i++) {
			//substring 이용해서 필요한 url 부분만 자름
			gimgs[i] = gimgs[i].substring(10, 135);
			imgs.add(gimgs[i]);
		}
	    
	}
	
	//제목이 아예 없어서 하나씩 땡겨지던거 빈칸 추가해서 해결
	titles.add(9, " ");
	
	//weca 코드
	String caurl = "http://www.weca.or.kr/donation/campaign.asp";
	String caselector = "div.services_wrapper>div.campaign_box";
	Document cadoc = null;
		    
	try {
		cadoc = Jsoup.connect(caurl).get(); // 1. get방식의 URL에 연결해서 가져온 값을 doc에 담는다.
	} catch (IOException e) {
		System.out.println(e.getMessage());
	}
		    
	//메인 요소 선택
	Elements weca = cadoc.select(caselector);
		    
	//weca title
	String[] catitles = weca.select("a>div.img_container>div.campaign_tex>dl>dt.tit").html().split("\n");
	for(int t=0; t<catitles.length; t++) {
		titles.add(catitles[t]);
	}
		    
	//weca img
	weca.select("a>div.img_container>div.campaign_img").remove();
	weca.select("a>div.img_container>div.campaign_tex").remove();
	String[] caimgs = weca.select("a>div.img_container").html().split("\n");
	for(int i=0; i<caimgs.length; i++) {
		caimgs[i] = "http://www.weca.or.kr" + caimgs[i].substring(10, 35);
		//indexOf로 "기준 문자 2개로 쪼갬 쪼갠거에 "은 포함x
		int idx = caimgs[i].indexOf('"');
		//쪼갠거 앞에 가져옴
		caimgs[i] = caimgs[i].substring(0,idx);
		imgs.add(caimgs[i]);
	}
		    
	//weca url
	weca.select("a>div.img_container").remove();
	String[] caurls = weca.html().split("\n");
	for(int u=0; u<caurls.length; u++) {
		if(u==3) {
			caurls[u] = "http://www.weca.or.kr" + caurls[u].substring(9, 27);
			urls.add(caurls[u]);
		}else {
			caurls[u] = "http://www.weca.or.kr" + caurls[u].substring(9, 53);
			urls.add(caurls[u]);
		}
	}
	
	
	
	
		//concern 코드
		String courl = "https://www.concern.or.kr/load.asp?subPage=310#";
		String coselector = "div.bbs_thumb_list>ul";
	    Document codoc = null;
	    
	    try {
	    	codoc = Jsoup.connect(courl).get(); // 1. get방식의 URL에 연결해서 가져온 값을 doc에 담는다.
	    } catch (IOException e) {
	        System.out.println(e.getMessage());
	    }
	    
	    //메인 요소 선택
	    Elements concern = codoc.select(coselector);
	    
	    //concern title
	    String[] cotitles = concern.select("li>div.cont>div.tit>a>span").html().split("\n");
	    for(int t=0; t<cotitles.length; t++) {
	    	//indexOf로 ]기준 문자 2개로 쪼갬 쪼갠거에 "은 포함x
	    	int idx = cotitles[t].indexOf(']');
	    	//쪼갠거에서 뒤에꺼 앞에서 2번째부터 가져옴
	    	cotitles[t] = cotitles[t].substring(idx+2);
	    	titles.add(cotitles[t]);
	    }
	    
	    //concern img
	    concern.select("li>a>div.over").remove();
		String[] coimgs = concern.select("li>a").html().split("\n");
		for(int i=0; i<coimgs.length; i++) {
			coimgs[i] = "https://www.concern.or.kr" + coimgs[i].substring(10, 63);
			imgs.add(coimgs[i]);
		}
	    
	    //concern url
		concern.select("li>div.cont>div.tit>div.date").remove();
		concern.select("li>div.cont>div.tit>a>span").remove();
		String[] courls = concern.select("li>div.cont>div.tit").html().split("\n");
		for(int u=0; u<courls.length; u++) {
			if(u<2) {
				courls[u] = "https://www.concern.or.kr" + courls[u].substring(63, 174);
				//replace로 "랑 ' 제거
				courls[u] = courls[u].replace('"',' ');
				courls[u] = courls[u].replace("'"," ");
				urls.add(courls[u]);
			}else {
				courls[u] = "https://www.concern.or.kr" + courls[u].substring(10, 91);
				urls.add(courls[u]);
			}
			
		}
		
		
	
	//withgo 코드
	
	for(int wg=1; wg<3; wg++) {
		String wurl = "http://www.withgo.or.kr/campaign/story_cam.asp?strArea=B&intCate=&intStat=1&intPage="+wg+"#";
		String wselector = "div.camp_list>ul.clearfix";
		Document wdoc = null;
		    
		try {
			wdoc = Jsoup.connect(wurl).get(); // 1. get방식의 URL에 연결해서 가져온 값을 doc에 담는다.
		} catch (IOException e) {
			System.out.println(e.getMessage());
		}
		    
		//메인 요소 선택
		Elements withgo = wdoc.select(wselector);
		    
		//withgo title
		String[] wtitles = withgo.select("li>a>p.tit").html().split("\n");
		for(int t=0; t<wtitles.length; t++) {
			titles.add(wtitles[t]);
		}
		    
		//withgo img
		String[] wimgs = withgo.select("li>a>div.thum").html().split("\n");
		for(int i=0; i<wtitles.length; i++) {
			wimgs[i] = "http://www.withgo.or.kr" + wimgs[i].substring(10,54);
			int idx = wimgs[i].indexOf('"');
			wimgs[i] = wimgs[i].substring(0,idx);
			imgs.add(wimgs[i]);
		}
			
		    
		//withgo url
		withgo.select("li>span").remove();
		withgo.select("li>div").remove();
		withgo.select("li>a>ul").remove();
		withgo.select("li>a>div.thum").remove();
		String[] wurls = withgo.select("li").html().split("\n");
		for(int u=0; u<wtitles.length; u++) {
			wurls[u] = "http://www.withgo.or.kr/campaign" + wurls[u].substring(10, 98).replace('"',' ');
			urls.add(wurls[u]);
		}
			
	}
	
	
	int count = titles.size();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tmargin-top:30px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.today{\r\n");
      out.write("\t\tpadding-top:7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.searchimg {\r\n");
      out.write("\t\twidth:18px;\r\n");
      out.write("\t\theight:18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginimg {\r\n");
      out.write("\t\twidth:30px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-right:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menudiv{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding-top:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem {\r\n");
      out.write("\t\tpadding: 0px 30px 0px 30px;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:600;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tfont-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem:hover {\r\n");
      out.write("\t\t/* color:#C3A88C; */\r\n");
      out.write("\t\tcolor:#EACC1A;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu {\r\n");
      out.write("\t\tcolor:#AB3839;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu:hover {\r\n");
      out.write("\t\tcolor:#F86C6B;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* .bcolor {\r\n");
      out.write("\t\tbackground:#888888;\r\n");
      out.write("\t} */\r\n");
      out.write("\t.logo {\r\n");
      out.write("\t\twidth:20px;\r\n");
      out.write("\t\theight:20px;\r\n");
      out.write("\t\tmargin-left:15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\" class=\"header\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<img class =\"logo\" src=\"imgs/logo.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-5\"></div>\r\n");
      out.write("\t\t<div class=\"col-sm-2 today\">\r\n");
      out.write("\t\t\t<span> Today with </span>\r\n");
      out.write("\t\t\t<span> 0 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\" aria-label=\"Search\" aria-describedby=\"button-addon2\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"><img class =\"searchimg\" src=\"imgs/search.png\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t<img class =\"loginimg\" src=\"imgs/loginimg.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"menudiv\">\r\n");
      out.write("\t\t\t\t<a href=\"donation.jsp\" class=\"menuitem give\" aria-current=\"false\"> 기부 </a>\r\n");
      out.write("\t\t\t\t<a href=\"volunteer.jsp\" class=\"menuitem\" aria-current=\"false\"> 봉사 </a>\r\n");
      out.write("\t\t\t\t<a href=\"campaign.jsp\" class=\"menuitem\" aria-current=\"false\"> 캠페인 </a>\r\n");
      out.write("\t\t\t\t<a href=\"drank.jsp\" class=\"menuitem\" aria-current=\"false\"> 기부순위 </a>\r\n");
      out.write("\t\t\t\t<a href=\"gogodonation.jsp\" class=\"menuitem redmenu\" aria-current=\"false\"> 기부해요 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<!-- 사이트 카드들 -->\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<strong style=\"padding-left:23px;\"> 기부 전체 <strong style=\"color:#E5CF51\">");
      out.print( count );
      out.write("</strong> 개</strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<!-- card1 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg1.png\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 생리대가 필요한 아이들 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 함께하는 한숲 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card1.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- card2 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg2.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 어르신들의 겨울을 따뜻하게 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 나눔코리아</span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card2.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- card3 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg3.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 공부가 하고싶어요 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 아프리카아시아난민교육후원회 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card3.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- card4 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg4.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 독거어르신들에게 특별한 하루를 선물하세요!! </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 용산재가노인지원센터 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card4.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row\">\t\r\n");
      out.write("\t\t<!-- card5 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg5.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 공부가 하고싶어요 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 아프리카아시아난민교육후원회 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card5.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- card6 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg6.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 공부가 하고싶어요 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 아프리카아시아난민교육후원회 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card6.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- card7 -->\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t\t<div class=\"card\"> \r\n");
      out.write("\t\t\t\t<img src=\"imgs/cimg7.jpg\" class=\"card_img\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"card_title\"> 공부가 하고싶어요 </strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"category\"> 아프리카아시아난민교육후원회 </span> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"card7.jsp\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 크롤링 카드들 -->\r\n");
      out.write("\t");

		for(int d=0; d<titles.size(); d++){
			
	
      out.write("\r\n");
      out.write("\t\t");
 
			String com = "";
			if(urls.get(d).contains("gfound")){
				com = "지파운데이션";
			}else if(urls.get(d).contains("weca")){
				com = "세계교육문화원 WECA";	
			}else if(urls.get(d).contains("concern")){
				com = "컨선월드와이드";
			}else if(urls.get(d).contains("withgo")){
				com = "함께하는 사랑밭";
			}
		
      out.write("\r\n");
      out.write("\t\t<div class=\"col-3\">\r\n");
      out.write("\t\t<div class=\"card\"> <img src=\"");
      out.print( imgs.get(d) );
      out.write("\" class=\"card_img\">\r\n");
      out.write("\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t<div class=\"info_bx\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"card_title\">");
      out.print( titles.get(d) );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t<div class=\"s_bx\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"category\"> ");
      out.print( com );
      out.write(" </span> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ss_bx\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print( urls.get(d) );
      out.write("\"><button id=\"btn\" >자세히 보기</button></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 1줄 만들때마다 있어야되서 if에 함 -->\r\n");
      out.write("\t\t");

			if(d==0|d%4==0){	
		
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

		}	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.fdiv{\r\n");
      out.write("\t\t/* background-color:#D1C6BA; */\r\n");
      out.write("\t\tbackground-color:#DDD18D;\r\n");
      out.write("\t\tmargin-top:20px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t\tpadding: 20px 30px 20px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.companyimg{\r\n");
      out.write("\t\twidth:15px;\r\n");
      out.write("\t\theight:15px;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"fdiv\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 서울특별시 성동구 살곶이길 200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 대표전화 : 02-2290-2200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<img class=\"companyimg\" src=\"imgs/company.png\">\r\n");
      out.write("\t\t<span> Copyright © InsideOut. All Rights Ressrved. </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
