/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-10-16 16:34:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fweb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/fweb/Top.jsp", Long.valueOf(1571243350121L));
    _jspx_dependants.put("/fweb/Bottom.jsp", Long.valueOf(1571238713987L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>꿀비</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"imgs/favicon.ico\" >\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" >\r\n");
      out.write("<style>\r\n");
      out.write("\t.carousel-indicators li {\r\n");
      out.write("\t\tborder-radius: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.detailMenuDiv {\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding: 30px 0px 30px 0px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #e8e9ed;\r\n");
      out.write("\t}\r\n");
      out.write("\t.detailIcon {\r\n");
      out.write("\t\twidth:30px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\talign:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.detailMenuItem {\r\n");
      out.write("\t\tpadding: 0px 30px 0px 30px;\r\n");
      out.write("\t\tfont-size:18px;\r\n");
      out.write("\t\tfont-weight:500;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tfont-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.detailMenuItem:hover {\r\n");
      out.write("\t\tcolor:#EACC1A;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.donationMain, .volunteerMain, .campaignMain{\r\n");
      out.write("\t\tpadding: 30px; \r\n");
      out.write("\t}\r\n");
      out.write("\t.smallTitle {\r\n");
      out.write("\t\tfont-size:15px;\r\n");
      out.write("\t\tfont-weight:500;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t}\r\n");
      out.write("\t.smallTitle:hover {\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.right_point {\r\n");
      out.write("\t\twidth:17px;\r\n");
      out.write("\t\theight:15px;\r\n");
      out.write("\t\tpadding-left:5px;\r\n");
      out.write("\t\tmargin-bottom:3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.imgwrap {\r\n");
      out.write("\t\theight:480px;\r\n");
      out.write("\t\tbackground:#CCB996;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cimg {\r\n");
      out.write("\t\theight:380px;\r\n");
      out.write("\t\tpadding: 50px 0px 50px 200px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"Resources/jquery/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Top 불러옴 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tmargin-top:30px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.today{\r\n");
      out.write("\t\tpadding-top:7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.searchimg {\r\n");
      out.write("\t\twidth:18px;\r\n");
      out.write("\t\theight:18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginimg {\r\n");
      out.write("\t\twidth:30px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-right:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menudiv{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding-top:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem {\r\n");
      out.write("\t\tpadding: 0px 30px 0px 30px;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:600;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tfont-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem:hover {\r\n");
      out.write("\t\t/* color:#C3A88C; */\r\n");
      out.write("\t\tcolor:#EACC1A;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu {\r\n");
      out.write("\t\tcolor:#AB3839;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu:hover {\r\n");
      out.write("\t\tcolor:#F86C6B;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* .bcolor {\r\n");
      out.write("\t\tbackground:#888888;\r\n");
      out.write("\t} */\r\n");
      out.write("\t.logo {\r\n");
      out.write("\t\twidth:20px;\r\n");
      out.write("\t\theight:20px;\r\n");
      out.write("\t\tmargin-left:15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\" class=\"header\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<img class =\"logo\" src=\"imgs/logo.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-5\"></div>\r\n");
      out.write("\t\t<div class=\"col-sm-2 today\">\r\n");
      out.write("\t\t\t<span> Today with </span>\r\n");
      out.write("\t\t\t<span> 0 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\" aria-label=\"Search\" aria-describedby=\"button-addon2\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"><img class =\"searchimg\" src=\"imgs/search.png\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t<img class =\"loginimg\" src=\"imgs/loginimg.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"menudiv\">\r\n");
      out.write("\t\t\t\t<a href=\"donation.jsp\" class=\"menuitem give\" aria-current=\"false\"> 기부 </a>\r\n");
      out.write("\t\t\t\t<a href=\"volunteer.jsp\" class=\"menuitem\" aria-current=\"false\"> 봉사 </a>\r\n");
      out.write("\t\t\t\t<a href=\"campaign.jsp\" class=\"menuitem\" aria-current=\"false\"> 캠페인 </a>\r\n");
      out.write("\t\t\t\t<a href=\"drank.jsp\" class=\"menuitem\" aria-current=\"false\"> 기부순위 </a>\r\n");
      out.write("\t\t\t\t<a href=\"gogodonation.jsp\" class=\"menuitem redmenu\" aria-current=\"false\"> 기부해요 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Center 들어갈 것들 -->\r\n");
      out.write("\t<div class=\"center\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 이벤트 등 슬라이드 이미지로 표시 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div id=\"hiCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#hiCarousel\" data-slide-to=\"0\" class=\"active\" style=\"width:10px;height:10px;\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#hiCarousel\" data-slide-to=\"1\" style=\"width:10px;height:10px;\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#hiCarousel\" data-slide-to=\"2\" style=\"width:10px;height:10px;\"></li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"carousel-item active\" data-interval=\"5000\">\r\n");
      out.write("\t\t\t\t    \t\t<div class=\"imgwrap w-100\">\r\n");
      out.write("\t\t\t\t    \t\t\t<img src=\"imgs/cimg3.jpg\" class=\"d-block cimg\">\r\n");
      out.write("\t\t\t\t    \t\t\t<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5> 공부가 하고싶어요 </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p> 아이들에게 공부함의 행복을 주세요 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    \t<div class=\"carousel-item\" data-interval=\"5000\">\r\n");
      out.write("\t\t\t\t      \t\t<img src=\"https://dummyimage.com/1140x480/000/fff\" class=\"d-block w-100\" alt=\"\">\r\n");
      out.write("\t\t\t\t      \t\t<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5> 오렌지는 왜 맛있을까 </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> 오렌지니까.. </p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t    \t<div class=\"carousel-item\" data-interval=\"5000\">\r\n");
      out.write("\t\t\t\t      \t\t<img src=\"https://dummyimage.com/1140x480/000/fff\" class=\"d-block w-100\" alt=\"\">\r\n");
      out.write("\t\t\t\t      \t\t<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5> 돈까스 먹고싶다 </h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p> 돈까스 최고존엄 </p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a class=\"carousel-control-prev\" href=\"#hiCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t  \t\t<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t  \t</a>\r\n");
      out.write("\t\t\t\t  \t<a class=\"carousel-control-next\" href=\"#hiCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t    \t<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t  \t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 상세 메뉴 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"detailMenuDiv\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"youth.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t<!--  <img src=\"imgs/children.png\" class=\"detailIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t<br>-->\r\n");
      out.write("\t\t\t\t\t\t\t아동•청소년\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"family.jsp\" class=\"detailMenuItem\" aria-current=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--  <img src=\"imgs/family.png\" class=\"detailIcon\">\r\n");
      out.write("\t\t\t\t\t\t\t<br> -->\r\n");
      out.write("\t\t\t\t\t\t\t가정 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"elderly.jsp\" class=\"detailMenuItem\" aria-current=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <img src=\"imgs/elderly.png\" class=\"detailIcon\"> \r\n");
      out.write("\t\t\t\t\t\t\t<br> -->\r\n");
      out.write("\t\t\t\t\t\t\t어르신 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"disabled.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t장애인 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"animal.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t동물 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"disaster.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t재난•재해 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"environment.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t환경 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"etc.jsp\" class=\"detailMenuItem\" aria-current=\"false\"> \r\n");
      out.write("\t\t\t\t\t\t\t기타 \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 기부 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"donationMain\">\r\n");
      out.write("\t\t\t\t\t<a href=\"donation.jsp\" class=\"smallTitle give\">\r\n");
      out.write("\t\t\t\t\t \t기부 <img src=\"imgs/right_point.png\" class=\"right_point\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 봉사 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"volunteerMain\">\r\n");
      out.write("\t\t\t\t\t<a href=\"volunteer.jsp\" class=\"smallTitle\">\r\n");
      out.write("\t\t\t\t\t\t봉사 <img src=\"imgs/right_point.png\" class=\"right_point\"> \r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 캠페인 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<div class=\"campaignMain\">\r\n");
      out.write("\t\t\t\t\t<a href=\"campaign.jsp\" class=\"smallTitle\"> \r\n");
      out.write("\t\t\t\t\t\t캠페인 <img src=\"imgs/right_point.png\" class=\"right_point\"> \r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.fdiv{\r\n");
      out.write("\t\t/* background-color:#D1C6BA; */\r\n");
      out.write("\t\tbackground-color:#DDD18D;\r\n");
      out.write("\t\tmargin-top:20px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t\tpadding: 20px 30px 20px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.companyimg{\r\n");
      out.write("\t\twidth:15px;\r\n");
      out.write("\t\theight:15px;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"fdiv\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 서울특별시 성동구 살곶이길 200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<span> 대표전화 : 02-2290-2200 </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<img class=\"companyimg\" src=\"imgs/company.png\">\r\n");
      out.write("\t\t<span> Copyright © InsideOut. All Rights Ressrved. </span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
