/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-10-16 16:29:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fweb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tmargin-top:30px;\r\n");
      out.write("\t\tmargin-bottom:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.today{\r\n");
      out.write("\t\tpadding-top:7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.searchimg {\r\n");
      out.write("\t\twidth:18px;\r\n");
      out.write("\t\theight:18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.loginimg {\r\n");
      out.write("\t\twidth:30px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-right:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menudiv{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding-top:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem {\r\n");
      out.write("\t\tpadding: 0px 30px 0px 30px;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t\tfont-weight:600;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tfont-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menuitem:hover {\r\n");
      out.write("\t\t/* color:#C3A88C; */\r\n");
      out.write("\t\tcolor:#EACC1A;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu {\r\n");
      out.write("\t\tcolor:#AB3839;\r\n");
      out.write("\t}\r\n");
      out.write("\t.redmenu:hover {\r\n");
      out.write("\t\tcolor:#F86C6B;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* .bcolor {\r\n");
      out.write("\t\tbackground:#888888;\r\n");
      out.write("\t} */\r\n");
      out.write("\t.logo {\r\n");
      out.write("\t\twidth:20px;\r\n");
      out.write("\t\theight:20px;\r\n");
      out.write("\t\tmargin-left:15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"Resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\" class=\"header\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<img class =\"logo\" src=\"imgs/logo.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-5\"></div>\r\n");
      out.write("\t\t<div class=\"col-sm-2 today\">\r\n");
      out.write("\t\t\t<span> Today with </span>\r\n");
      out.write("\t\t\t<span> 0 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\" aria-label=\"Search\" aria-describedby=\"button-addon2\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"><img class =\"searchimg\" src=\"imgs/search.png\"></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-1\">\r\n");
      out.write("\t\t\t<img class =\"loginimg\" src=\"imgs/loginimg.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<div class=\"menudiv\">\r\n");
      out.write("\t\t\t\t<a href=\"donation.jsp\" class=\"menuitem give\" aria-current=\"false\"> 기부 </a>\r\n");
      out.write("\t\t\t\t<a href=\"volunteer.jsp\" class=\"menuitem\" aria-current=\"false\"> 봉사 </a>\r\n");
      out.write("\t\t\t\t<a href=\"campaign.jsp\" class=\"menuitem\" aria-current=\"false\"> 캠페인 </a>\r\n");
      out.write("\t\t\t\t<a href=\"drank.jsp\" class=\"menuitem\" aria-current=\"false\"> 기부순위 </a>\r\n");
      out.write("\t\t\t\t<a href=\"gogodonation.jsp\" class=\"menuitem redmenu\" aria-current=\"false\"> 기부해요 </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
